### ISSUE TITLE
requestify blocks lose recipes

### ISSUE THREAD

**Issue by jdratlif** [Buuz135/RS-Requestify#11]
I'm not sure what triggers it, but several times I've come back to my world to see that all my requestor blocks have no recipe anymore.

I opened the block UI, put the block I wanted in (e.g. oak planks), set the number to 256 and hit save. The planks were made and things looked fine. Then later I come back to my world and the requestor is empty. Same things happens with all my requestor blocks (only have 2 right now - one for oak planks and one for glass).

Not sure what information would be helpful here.

MC 1.12.2
Requestify 1.12.2-1.0.2-3
RS 1.6.16
Forge 14.23.5.2854

**Comment by jdratlif** [comment]
I think I've narrowed it down. It happens when I quit the minecraft client. I can quit one world and enter another, but if I quit the client, it loses the configuration.

This is a 1 minute video demonstrating the problem:
http://www.technoplaza.net/temp/requestify-bug.mp4

This is a link to an export of my mod pack with my world, mod configs, crafttweaker scripts, and logs. It should be importable with the Twitch client or GD Launcher.

http://www.technoplaza.net/temp/skytania.zip

Complete Mod List:

AppleSkin
AromaBackup
Bad Wither No Cookie
Baubles
Bed Patch
Better Builder's Wands
BetterFps
Botania
Building Gadgets
Chisel
Clay Bucket
Click Machine
Clumps
Controlling
Crafting Station
CraftTweaker
Ender Storage
Environmental Creepers
Ex Compressum
Ex Nihilo Creatio
Flux Networks
FoamFix
Glassential
InGame Info XML
Initial Inventory
Inventory Tweaks
Iron Chests
JEI
JEI Integration
KleeSlabs
Mob Grinding Utils
ModTweaker
More Overlays
Mouse Tweaks
Neat
NotEnoughScaffold
Ore Excavation
Quark
RE-Sound
ReAuth
Reborn Storage
Refined Storage
Refined Storage Addons
Refined Storage Requestify
RFTools
RFTools Control
Simply Jetpacks 2
Snad
Storage Drawers
Super Sound Muffler: Revived
The One Probe
The Weirding Gadget
Thermal Dynamics
Thermal Expansion
Tiny Mob Farm
Tiny Progressions
Tomb Many Graves 2
TOP Addons
Translocators
Twerk Sim 2K16
VanillaFix
XNet
YUNoMakeGoodMap

**Comment by jdratlif** [comment]
I had some success using a chunk loader in the same block space that the requester was in. I'm not sure why that would be, but I know external storage attached to storage drawer controllers sometimes have trouble when restarting if they're not chunk loaded.

**Comment by Buuz135** [comment]
Can't replicate in latest
