### ISSUE TITLE
[1.12.2][Feature] Add option to craft despite missing items/fluids (best effort setting) | "Partial Jobs"

### ISSUE THREAD

**Issue by david-kalbermatten** [Buuz135/RS-Requestify#12]
### Versions
Minecraft Version: 1.12.2
Forge Version: forge-14.23.5.2854
Mod Version: 1.12.2-1.0.2-3

### Observed Behavior
The requester only sends a crafting job if the full amount (the difference between stored and requested) can be crafted.

stored 20, requested 50 = job for 30
Only executes if all the resources are available

### Requested Behavior
The requester should have some kind of 'best effort' setting where it crafts as much as currently possible i.e. sends the biggest currently possible job, instead of doing nothing.

### Reasoning/Use Case
On my server, I have an automation set up where fluid cows produce liquid metal which is imported into refined storage and then converted with a fluid auto crafting recipe. The requester is used to keep the ingot version of the metal/item in stock. However, this only works if there is more liquid metal than the requested amount uses, otherwise, it doesn't do anything.

As you can see in the screenshots below, there is enough resonant ender in the system to at least craft another 52 ender pearls...

### Screenshots
![image](https://user-images.githubusercontent.com/45201085/97209440-a1285e80-17bc-11eb-9f74-3dfa25b465b7.png)
![image](https://user-images.githubusercontent.com/45201085/97209612-d92fa180-17bc-11eb-82f1-b1e0417cb86a.png)
![image](https://user-images.githubusercontent.com/45201085/97209644-e482cd00-17bc-11eb-871b-8cf7db70e9da.png)
![image](https://user-images.githubusercontent.com/45201085/97209672-ea78ae00-17bc-11eb-9324-075d21927338.png)
![image](https://user-images.githubusercontent.com/45201085/97209694-f1072580-17bc-11eb-8821-22056308d54e.png)

**Comment by Letoric** [comment]
This definitely needs to be present, the mod is a great idea, but partial jobs really needs to be part of maintaining a stock.

**Comment by david-kalbermatten** [comment]
I figured out how you can work around it. The simplest solution is to lower the number of `MAX_CRAFT_AMOUNT`, this way it crafts stuff even if you don't have all the needed materials for the amount you set in the requester ;D
```properties
# Configuration file

general {
    # The maximum amount requested as a craft by the Requester. It will still achieve the desired amount but in smaller crafting batches. (A sanity server check)
    # Min: 1
    # Max: 2147483647
    I:MAX_CRAFT_AMOUNT=128
}
```

**Comment by Letoric** [comment]
I remember seeing that it *should* have a config, however, I don't see that
it created one.

**Comment by david-kalbermatten** [comment]
the config file is called `refinedstoragerequestify.cfg`

**Comment by Letoric** [comment]
Ahh I over looked it since it didn't match the jar naming style. Thanks

**Comment by Letoric** [comment]
Can you please re-check the code that it's creating the file? I've tried in
a fresh world, in single player, and in an existing world, none of them get
a config file either in Config or world\serverconfig directories.

In the mean time, can we manually create it? 1.16.3 uses TOML files, not
CFG files

**Comment by david-kalbermatten** [comment]
> In the mean time, can we manually create it? 1.16.3 uses TOML files, not
CFG files

@Letoric I have no idea... I'm not the maintainer. Another thing, please don't ask for specifics when using a different version from  OP. I only used this mod on 1.12.2

If you have an issue with the config files on 1.16.3 open up another issue and report the bug.

**Comment by Letoric** [comment]
I don't think the version was mentioned when I first looked, or I overlooked it. I'll make a separate post
