### ISSUE TITLE
Server crash on right-clicking block

### ISSUE THREAD

**Issue by Schokofabrik** [Buuz135/RS-Requestify#13]
When I right-clicked the block, the server just crashed.
Crash logs:

[crash-2020-10-29_16.15.27-server.txt](https://github.com/Buuz135/RS-Requestify/files/5464452/crash-2020-10-29_16.15.27-server.txt)
[crash-2020-10-29_16.14.28-server.txt](https://github.com/Buuz135/RS-Requestify/files/5464453/crash-2020-10-29_16.14.28-server.txt)

**Comment by Buuz135** [comment]
Update the mod
