### ISSUE TITLE
[1.12.2][Feature] More than one item per block

### ISSUE THREAD

**Issue by david-kalbermatten** [Buuz135/RS-Requestify#14]
### Versions
Minecraft Version: 1.12.2
Forge Version: forge-14.23.5.2854
Mod Version: 1.12.2-1.0.2-3

### Observed Behavior
The requester can only hold one item/liquid

### Requested Behavior
The requester should either have storage upgrade slots, so you can increase the number of different items/fluids that can be requested by one block or the requester should just come with 9 slots out of the box.

Even better idea. Have multiple tiers for the requester. With each tier, the requester can handle more items/fluids per block. One way to do this might be having the requester block and a requester core which can be upgraded like the storage cells and then inserted into the requester block.

### Reasoning/Use Case
Once your auto-crafting setup reaches a certain level it becomes tedious to setup requesters for all the items you want to keep stocked. Even if you do set up all the requesters, you still have to build up to 9 requesters per crafter which can take up a lot of space.

**Comment by RGFTheCoder** [comment]
The requester is designed for >64 tasks. For multiple items you can use an interface+crafting upgrade+external storage, or spend the time setting up the requesters
