### ISSUE TITLE
[1.16.4] Can't Keep 64 Tertium Essence Crafted

### ISSUE THREAD

**Issue by HSparks17** [Buuz135/RS-Requestify#18]
As stated, all other essence from Mystical Agriculture work perfectly fine, but when it comes to the Tertium essence, it is completely unable to maintain 64. I'm using 4 RFTools Crafter Tier 1's, each with their own Crafter and essence type. I'm not sure if this is user error or not but it seems like everything is setup fine, just that it isn't cooperating very well.

**Comment by Buuz135** [comment]
Maybe you didn't have enough for them to craft, should be improved https://github.com/Buuz135/RS-Requestify/commit/66e0d37af8321c7bc210a6d67ab291ba173532b3
