### ISSUE TITLE
Horribly coded text window

### ISSUE THREAD

**Issue by KingDomino** [Buuz135/RS-Requestify#20]
Playing the latest version on 1.16.5 and the requester must be broken to reset the text value to 0. Also, game crashes when a text value goes over the max integer limit, something even the most basic of mods don't have an issue with.

**Comment by Buuz135** [comment]
Thanks for the report, but you are a terrible person and you should not talk to people.

**Comment by Adrigorithm** [comment]
> something even the most basic of mods don't have an issue with.

Very well then, you seem to know an awful lot about how **most basic of mods** are coded. Why don't you make a PR?

**Comment by KingDomino** [comment]
Hello, I'd like to apologize for my behavior when creating this Github issue last night. It was late and I was in a bad mood and I used it as an excuse to take it out on you instead of being polite when making my report. If there's anything that can be done for you to forgive me, let me know please.

**Comment by dualmacops** [comment]
I would like to add that (at least for me) the numpad doesn't seem to work.
