### ISSUE TITLE
Support for More Refined Storage

### ISSUE THREAD

**Issue by aking4125** [Buuz135/RS-Requestify#37]
Hello,

Using [More refined storage](https://legacy.curseforge.com/minecraft/mc-mods/morerefinedstorage) causes the game to crash upon load with this mod installed.

https://github.com/tth05/morerefinedstorage/issues/58

https://mclo.gs/ZVUB3Fu

Perhaps something is outdated which still requires the old RS. Any ideas?

**Comment by Buuz135** [comment]
Nah, this is a RS addon, I would need to do a new mod.
